// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeo5JBNa3EgA5aL6WQyGOM8fJ9dfPkeUc',
    appId: '1:14928407645:web:dafe4205eafa8010ea71b4',
    messagingSenderId: '14928407645',
    projectId: 'flutter-gemini-chat-app',
    authDomain: 'flutter-gemini-chat-app.firebaseapp.com',
    storageBucket: 'flutter-gemini-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuZWqQf1Ygau48kX5Iqi6V6M91ZQMOL5E',
    appId: '1:14928407645:android:f1eb7efb9bee5471ea71b4',
    messagingSenderId: '14928407645',
    projectId: 'flutter-gemini-chat-app',
    storageBucket: 'flutter-gemini-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwa3XKnwdtU3CDDx_R5RmuSSfW4aYCUyg',
    appId: '1:14928407645:ios:38ffda34fff630e9ea71b4',
    messagingSenderId: '14928407645',
    projectId: 'flutter-gemini-chat-app',
    storageBucket: 'flutter-gemini-chat-app.appspot.com',
    iosBundleId: 'com.example.flutterChatGoogleAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwa3XKnwdtU3CDDx_R5RmuSSfW4aYCUyg',
    appId: '1:14928407645:ios:039ede14c5b69246ea71b4',
    messagingSenderId: '14928407645',
    projectId: 'flutter-gemini-chat-app',
    storageBucket: 'flutter-gemini-chat-app.appspot.com',
    iosBundleId: 'yes',
  );
}
